services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

#  base_service:
#    build: ./base_service
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#    env_file:
#      - .env

  type_1_publisher_service:
    build: ./type_1_publisher_service
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    deploy:
        replicas: 3

  type_2_publisher_service:
    build: ./type_2_publisher_service
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env

  type_3_publisher_service:
    build: ./type_3_publisher_service
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
