services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

#  base_service:
#    build: ./base_service
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#    env_file:
#      - .env

  publisher_type_1_events:
    build: publisher_type_1_events
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    deploy:
        replicas: 3

  publisher_type_2_events:
    build: publisher_type_2_events
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env

  publisher_type_3_events:
    build: publisher_type_3_events
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env

  consumer_type_1_events:
    build: consumer_type_1_events
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    deploy:
      replicas: 2

  consumer_type_2_events:
    build: consumer_type_2_events
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env

  consumer_type_4_events:
    build: consumer_type_4_events
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env

  consumer_type_3_publisher_type_4:
    build: consumer_type_3_publisher_type_4
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env